name: Testar script Python com token secreto

on:
  workflow_dispatch: # roda manualmente no GitHub Actions

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Criar token.json a partir do secret
      run: |
        printf '%s' "${{ secrets.GCP_TOKEN_JSON }}" > token.json

    - name: Instalar dependências
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Rodar script
      run: |
        source venv/bin/activate
        python HU-UFRR.py
