name: Process Token JSON

on:
  push:
    branches: 
      - main

jobs:
  process-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Process token
        env:
          TOKEN_JSON: ${{ secrets.token_json }}
        run: |
          printf "%s" "$TOKEN_JSON" > token.json
          python test.py
