name: Print Staging Message

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Staging Message
        run: echo "${{ secrets.TOKEN_JSON }}"
